### ISSUE TITLE
Encrypted Messages

### ISSUE THREAD

**Issue by ricardoperovano** [mgp25/Chat-API-NET#134]
@mgp25  why are you locking the issues?
the solution I gave is working without libaxolotl, i just changed the code and it worked. There are many people with this problem and it could help them for now. Thanks

**Comment by mgp25** [comment]
@ricardoperovano that will make most of numbers to be blocked. Thats why, there is always a reason for the changes we do

**Comment by ricardoperovano** [comment]
oK, I will keep testing it until there is a official solution here. Thanks Again!

**Comment by fuad86** [comment]
hiii @ricardoperovano can you tell to me, how the solution? my email is it.nanang@yahoo.com
Thank You

**Comment by criolo** [comment]
What dou you think about this: https://github.com/langboost/libaxolotl-uwp

**Comment by alijundi** [comment]
Yep! https://github.com/langboost/libaxolotl-uwp should work!

**Comment by sanjayradadiya91** [comment]
@alijundi  how to use this api actually i have no idea

**Comment by criolo** [comment]
@mgp25 I change this settings on WhatsAppApi.Settings.WhatsConstants and I receive no more crypto msgs.

public const string WhatsAppVer = "2.12.12";
public const string Device = "iPhone_5S";
public const string UserAgent = "WhatsApp/2.12.12 iPhone_OS/9.2 Device/iPhone_5S";

this setting is from my Iphone device, It can be done?

**Comment by mgp25** [comment]
Do what you want, im not responsible if you account gets blocked

**Comment by alijundi** [comment]
Hi @mgp25 I shall wait for the update for the api to include the libaxolotl encryption before using. Please let me know if you need any thing.

**Comment by criolo** [comment]
@mgp25 I'm simulating an Iphone access @ this version (my cellphone real version) why this may block my account?

**Comment by mgp25** [comment]
WhatsApp is forcing some specific things in WhatsApp, if you dont do it that way its easy to detect, if you want to use it go for it, but i dont recommend it. If you want try porting Chat API here, send pull requests and ill merge them

Regards

**Comment by criolo** [comment]
@mgp25 the https://github.com/langboost/libaxolotl-uwp for (.NET) is build to use as Windows APP (W10/Universal Windows) I cant compile this solution (have no Windows dev licence), but I see they have a good example for how to use after compile https://github.com/langboost/axolotl-sample-client/blob/master/SampleClient/SampleClient/Axolotl.xaml.cs

**Comment by criolo** [comment]
@mgp25 I already have ported from Windows App (w10/Universal Windows) but I've used another lib for curve25519 (https://github.com/hanswolff/curve25519) and this lib is throwing me StackOverFlow exp, can I send you the ported project?

**Comment by PieterFouche** [comment]
There is also this .Net version https://github.com/Muraad/libaxolotl-net

**Comment by criolo** [comment]
@KoosKombuis libaxolotl-net has some reference errors, I fixed and now it's compiling OK. Later when I go home I'll git it. Finally we can try to implement this on Chat-API-NET. Making @mgp25 happy LOL:-)

**Comment by GilairdiOliveira** [comment]
@criolo  advanced a part , but it must review all the change in the WA 1.6 had several design changes in php if you want to download and advance their work.
http://www.4shared.com/zip/lsH8GmTUba/Chat-API-NET-master.html

**Comment by KoosKombuis** [comment]
There seems to be a global WhatsApp outage, hope you guys did break anything ;-)

**Comment by mrjoebudi** [comment]
Login , send messages Work..!! but still can't  recieve message from target chat, why

**Comment by GHFoz** [comment]
We have to review what was already implemented in php module and adjust the changes of WA 1.6 in chat -net

**Comment by criolo** [comment]
@GHFoz TY, I'll see your attachment.

**Comment by SR91** [comment]
can we have any solution for decrypt received messages ?

**Comment by GHFoz** [comment]
@mgp25 is working on this.

**Comment by andrekat** [comment]
some1 knows if SendSetPhoto and SendStatusUpdate (for setting profile picture) is depending on libaxolol encryption? i dont get any error response .. node is successfully sent i guess  - for more info see [this post](https://github.com/mgp25/Chat-API-NET/issues/133)

**Comment by Yeremi0589** [comment]
Hi I'm having the same problem in method "OnGetMessage" I get in an encrypted message code, they have the solution let her know.

none have another alternative?

**Comment by ricardoperovano** [comment]
I have an alternative but as mpg25 said whatsapp could block your number.
Im using it and i was not blocked until now. If you want give me your
email. But use it as your own risk.
Em 04/01/2016 18:40, "Yeremi0589" <notifications@github.com> escreveu:

**Comment by Yeremi0589** [comment]
No problem my email is yeremi.alfaro@yahoo.es, I thank you

**Comment by Yeremi0589** [comment]
No problem my email is yeremi.alfaro@yahoo.es, I thank you

**Comment by ricardoperovano** [comment]
Just to remind you that the solution I have is still working til now!

**Comment by GHFoz** [comment]
@mgp25 have news?

**Comment by israellot** [comment]
I could sponsor the issue. Anyone else? Anyone available to implement a solution?

**Comment by KoosKombuis** [comment]
@israellot I can help.Do you know exactly what needs to be done?

**Comment by mrjoebudi** [comment]
recieve  message still encripted , can you the solution, i've install
package manager on VB. net

PM> Install-Package libaxolotl-uwp   ( succesfull ) but still encripted

2016-01-15 18:55 GMT+07:00 KoosKombuis <notifications@github.com>:

**Comment by Borriez** [comment]
@KoosKombuis
Is daar 'n manier dat ek jou direk kan kontak? Ek het Nov 2015 laas met WhatsAppApi gewerk en ek is nie op hoogte van al die veranderinge nie. Tans word elke simkaart van my direk geblok nadat ek hom registreer met Wart. Indien ek jou asb kan kontak, my nr is 0833799113.

**Comment by florisrobbemont** [comment]
@mgp25 Do you have any news on this?

**Comment by kwailo888** [comment]
I've done some work on this problem and have almost solved it. I've published my work so far here: https://github.com/kwailo888/MyChat-API-NET. The axolotl and curve libraries are both completed, the problem i'm facing right now is in the send retry node which is giving me an error 400. please take a look and see if you can help me solve these final steps. (the whatsappapi library is modified for my purposes in a few places nothing breaking just some extra return values)

**Comment by florisrobbemont** [comment]
That's awesome! 
I am working on this tomorrow and all next week. I'll clone your code and try to fix the 400 error.

**Comment by mgp25** [comment]
@kwailo888 send a pull request

**Comment by kwailo888** [comment]
@mgp25 Pull request Sent .. hope your able to see where i'm blind in this code :)

**Comment by emrahcetiner** [comment]
@kwailo888 i've download your commit (bcd8e872f7873eaba4f73e410506c1cb3f30a02c) and still encrypted.

**Comment by GKG4** [comment]
@mgp25 I am not an active user, recently came to know about this API.
Is there any solution for encrypted messages?
When I am sending from Android, its receiving fine, but when tried with IPhone, getting encrypted messages.

**Comment by Harshaddarji** [comment]
Can any one provide the solution for encrypted message from whatsAPP.

**Comment by florisrobbemont** [comment]
I'm currently working on a solution based on @kwailo888 's code. Hopefully have something today or monday.

**Comment by mgp25** [comment]
@Harshaddarji php version works perfectly

**Comment by florisrobbemont** [comment]
Yes, I'm porting the PHP encryption bits right now

**Comment by vivekanandrajak** [comment]
I am using csharp version for this API, Message received from WA is encrypted, need help to resolve in csharp version.

**Comment by pablokerestezachi** [comment]
I need this change. How can I help you guys?

Saludos,
Pablo

**Comment by kwailo888** [comment]
OK some great new guys .. I've got my version of it working :) .. not perfect yet but can decrypt .. will upload a test model by tomorrow :)

**Comment by pablokerestezachi** [comment]
Perfect!!! Good Job!!

Saludos,
Pablo

**Comment by SR91** [comment]
@kwailo888  its possible to decrypt received messeges ?

**Comment by kuldeepshah** [comment]
@kwailo888 have you post Changes ?

**Comment by darrenbehnke** [comment]
@kwailo888 please can you upload your version to test. Really need to Decrypt these messages.
Thank you

**Comment by kwailo888** [comment]
working sample is here : https://github.com/kwailo888/AxolotlTest

**Comment by darrenbehnke** [comment]
Thanks....will test it out now

**Comment by GKG4** [comment]
Still not working, getting issue as attached

![error](https://cloud.githubusercontent.com/assets/1776486/12808784/b3e500ba-cb3f-11e5-9f47-b6e763e201cb.PNG)

**Comment by darrenbehnke** [comment]
I am experiencing the same issue. Is this encoded into another format @kwailo888 ?

**Comment by mgp25** [comment]
@kwailo888 contact with me via mail

Regards
